"""Curated UI smoke examples. The UI agent chooses their order and focus."""

from __future__ import annotations

from agentic_api_qa.models import UISmokeCase


def alexpavsky_ui_smoke_catalog() -> list[UISmokeCase]:
    """Return 30 independent, production-safe UI candidates for alexpavsky.com."""

    return [
        UISmokeCase(
            case_id="ui-home-desktop",
            name="Desktop homepage renders",
            category="smoke",
            objective="Verify the primary page, title, hero, and main navigation render.",
            expected_text=["AI Testing & Integration", "Feed", "Explore", "Tools"],
            design_checkpoint=True,
        ),
        UISmokeCase(
            case_id="ui-primary-navigation",
            name="Primary navigation is discoverable",
            category="navigation",
            objective="Verify the core in-page destinations are exposed to users.",
            expected_text=["Feed", "Explore", "Tools", "Challenge", "Digest"],
        ),
        UISmokeCase(
            case_id="ui-theme-toggle",
            name="Theme toggle responds",
            category="interaction",
            objective="Open the alternate visual theme and capture the resulting state.",
            actions=[{"tool": "browser_click", "arguments": {"target": "#theme-toggle", "element": "theme toggle"}}],
            expected_text=["Toggle theme"],
            design_checkpoint=True,
        ),
        UISmokeCase(
            case_id="ui-mobile-menu",
            name="Mobile navigation opens",
            category="responsive",
            objective="Verify the compact navigation can be opened at a phone viewport.",
            viewport_width=390,
            viewport_height=844,
            actions=[{"tool": "browser_click", "arguments": {"target": "#nav-menu-btn", "element": "mobile menu button"}}],
            expected_text=["Feed", "Explore", "Tools"],
            design_checkpoint=True,
        ),
        UISmokeCase(
            case_id="ui-login-modal",
            name="Login modal opens",
            category="authentication",
            objective="Verify the unauthenticated login entry point and required controls.",
            actions=[{"tool": "browser_click", "arguments": {"target": "#auth-btn", "element": "login button"}}],
            expected_text=["Login", "Email", "Password"],
            design_checkpoint=True,
        ),
        UISmokeCase(
            case_id="ui-registration-tab",
            name="Registration view opens",
            category="authentication",
            objective="Verify users can switch from login to account registration without submitting data.",
            actions=[
                {"tool": "browser_click", "arguments": {"target": "#auth-btn", "element": "login button"}},
                {"tool": "browser_click", "arguments": {"target": "#auth-overlay button:has-text('Register')", "element": "register tab"}},
            ],
            expected_text=["Register", "Name", "Email", "Password"],
        ),
        UISmokeCase(
            case_id="ui-registration-fields",
            name="Registration fields accept draft input",
            category="form",
            objective="Verify registration fields accept harmless synthetic draft values; do not submit.",
            actions=[
                {"tool": "browser_click", "arguments": {"target": "#auth-btn", "element": "login button"}},
                {"tool": "browser_click", "arguments": {"target": "#auth-overlay button:has-text('Register')", "element": "register tab"}},
                {"tool": "browser_fill_form", "arguments": {"fields": [
                    {"target": "#reg-name", "name": "Name", "type": "textbox", "value": "QA Smoke User"},
                    {"target": "#reg-email", "name": "Email", "type": "textbox", "value": "qa-smoke@example.test"},
                    {"target": "#reg-password", "name": "Password", "type": "textbox", "value": "DraftOnly-123!"},
                    {"target": "#reg-password2", "name": "Confirm password", "type": "textbox", "value": "DraftOnly-123!"},
                ]}},
            ],
            expected_text=["Create Account"],
        ),
        UISmokeCase(
            case_id="ui-chat-opens",
            name="AI chat opens",
            category="chat",
            objective="Verify the floating AI assistant exposes its consent or conversation surface.",
            actions=[{"tool": "browser_click", "arguments": {"target": "#chat-toggle", "element": "chat toggle"}}],
            expected_text=["Chat"],
            design_checkpoint=True,
        ),
        UISmokeCase(
            case_id="ui-chat-terms",
            name="Chat terms are reachable",
            category="chat",
            objective="Verify consent terms can be opened before a user starts chatting.",
            actions=[
                {"tool": "browser_click", "arguments": {"target": "#chat-toggle", "element": "chat toggle"}},
                {"tool": "browser_click", "arguments": {"target": "#chat-terms-link", "element": "chat terms link"}},
            ],
            expected_text=["Terms"],
        ),
        UISmokeCase(
            case_id="ui-chat-consent",
            name="Chat consent unlocks input",
            category="chat",
            objective="Verify explicit consent unlocks the chat input without sending a message.",
            actions=[
                {"tool": "browser_click", "arguments": {"target": "#chat-toggle", "element": "chat toggle"}},
                {"tool": "browser_click", "arguments": {"target": "#chat-consent-cb", "element": "chat consent checkbox"}},
                {"tool": "browser_click", "arguments": {"target": "#chat-consent-btn", "element": "agree and start chat button"}},
            ],
            expected_text=["Ask"],
            design_checkpoint=True,
        ),
        UISmokeCase(
            case_id="ui-feed-section",
            name="Live feed section renders",
            category="content",
            objective="Verify the primary dynamic content section remains discoverable.",
            path="/#feed",
            expected_text=["LIVE"],
        ),
        UISmokeCase(
            case_id="ui-explore-section",
            name="Explore cards render",
            category="content",
            objective="Verify exploratory QA content and cards render.",
            path="/#explore",
            expected_text=["Explore"],
        ),
        UISmokeCase(
            case_id="ui-tools-section",
            name="Tools section renders",
            category="content",
            objective="Verify the tools area remains present and readable.",
            path="/#tools",
            expected_text=["Tools"],
        ),
        UISmokeCase(
            case_id="ui-newsletter-draft",
            name="Newsletter accepts draft email",
            category="form",
            objective="Verify the digest field accepts a synthetic address without submitting.",
            path="/#digest",
            actions=[{"tool": "browser_fill_form", "arguments": {"fields": [
                {"target": "#newsletter-email", "name": "Newsletter email", "type": "textbox", "value": "qa-smoke@example.test"}
            ]}}],
            expected_text=["Digest"],
        ),
        UISmokeCase(
            case_id="ui-keyboard-focus",
            name="Keyboard focus traversal works",
            category="accessibility",
            objective="Verify a keyboard user can advance focus through interactive controls.",
            actions=[
                {"tool": "browser_press_key", "arguments": {"key": "Tab"}},
                {"tool": "browser_press_key", "arguments": {"key": "Tab"}},
                {"tool": "browser_press_key", "arguments": {"key": "Tab"}},
            ],
            expected_text=["Feed"],
            design_checkpoint=True,
        ),
        UISmokeCase(
            case_id="ui-tablet-home",
            name="Tablet homepage renders",
            category="responsive",
            objective="Check the main visual hierarchy at a common tablet viewport.",
            viewport_width=820,
            viewport_height=1180,
            expected_text=["AI Testing & Integration", "Live Feed"],
            design_checkpoint=True,
        ),
        UISmokeCase(
            case_id="ui-small-mobile-home",
            name="Small mobile homepage renders",
            category="responsive",
            objective="Check the minimum supported mobile width for clipping and missing content.",
            viewport_width=320,
            viewport_height=700,
            expected_text=["AI Testing & Integration"],
            design_checkpoint=True,
        ),
        UISmokeCase(
            case_id="ui-mobile-theme-toggle",
            name="Mobile theme toggle responds",
            category="responsive",
            objective="Verify alternate theme controls remain operable on mobile.",
            viewport_width=390,
            viewport_height=844,
            actions=[{"tool": "browser_click", "arguments": {"target": "#theme-toggle", "element": "theme toggle"}}],
            expected_text=["Toggle theme"],
            design_checkpoint=True,
        ),
        UISmokeCase(
            case_id="ui-mobile-login-modal",
            name="Mobile login modal opens",
            category="authentication",
            objective="Verify the login modal remains usable at phone width.",
            viewport_width=390,
            viewport_height=844,
            actions=[{"tool": "browser_click", "arguments": {"target": "#auth-btn", "element": "login button"}}],
            expected_text=["Login", "Email", "Password"],
            design_checkpoint=True,
        ),
        UISmokeCase(
            case_id="ui-mobile-registration-tab",
            name="Mobile registration view opens",
            category="authentication",
            objective="Verify registration controls remain available on mobile.",
            viewport_width=390,
            viewport_height=844,
            actions=[
                {"tool": "browser_click", "arguments": {"target": "#auth-btn", "element": "login button"}},
                {"tool": "browser_click", "arguments": {"target": "#auth-overlay button:has-text('Register')", "element": "register tab"}},
            ],
            expected_text=["Register", "Create Account"],
            design_checkpoint=True,
        ),
        UISmokeCase(
            case_id="ui-mobile-chat-opens",
            name="Mobile AI chat opens",
            category="chat",
            objective="Verify the chat overlay is reachable at phone width.",
            viewport_width=390,
            viewport_height=844,
            actions=[{"tool": "browser_click", "arguments": {"target": "#chat-toggle", "element": "chat toggle"}}],
            expected_text=["Chat"],
            design_checkpoint=True,
        ),
        UISmokeCase(
            case_id="ui-login-draft-fields",
            name="Login fields accept draft input",
            category="authentication",
            objective="Verify login inputs accept harmless synthetic data without submitting.",
            actions=[
                {"tool": "browser_click", "arguments": {"target": "#auth-btn", "element": "login button"}},
                {"tool": "browser_fill_form", "arguments": {"fields": [
                    {"target": "#login-email", "name": "Email", "type": "textbox", "value": "qa-smoke@example.test"},
                    {"target": "#login-password", "name": "Password", "type": "textbox", "value": "DraftOnly-123!"},
                ]}},
            ],
            expected_text=["Forgot password"],
        ),
        UISmokeCase(
            case_id="ui-login-close",
            name="Login modal closes",
            category="authentication",
            objective="Verify users can dismiss authentication without side effects.",
            actions=[
                {"tool": "browser_click", "arguments": {"target": "#auth-btn", "element": "login button"}},
                {"tool": "browser_click", "arguments": {"target": "#auth-modal-close", "element": "close login modal"}},
            ],
            expected_text=["Login"],
        ),
        UISmokeCase(
            case_id="ui-register-back-to-login",
            name="Registration can return to login",
            category="authentication",
            objective="Verify authentication tabs can be switched in both directions.",
            actions=[
                {"tool": "browser_click", "arguments": {"target": "#auth-btn", "element": "login button"}},
                {"tool": "browser_click", "arguments": {"target": "#auth-overlay button:has-text('Register')", "element": "register tab"}},
                {"tool": "browser_click", "arguments": {"target": "#auth-overlay button:has-text('Login')", "element": "login tab"}},
            ],
            expected_text=["Forgot password"],
        ),
        UISmokeCase(
            case_id="ui-chat-close",
            name="AI chat closes",
            category="chat",
            objective="Verify users can dismiss the chat without sending a message.",
            actions=[
                {"tool": "browser_click", "arguments": {"target": "#chat-toggle", "element": "chat toggle"}},
                {"tool": "browser_click", "arguments": {"target": "#chat-close", "element": "close chat"}},
            ],
            expected_text=["AI Testing & Integration"],
        ),
        UISmokeCase(
            case_id="ui-challenge-section",
            name="Challenge section renders",
            category="content",
            objective="Verify the interactive challenge entry point is present.",
            path="/#challenge",
            expected_text=["Challenge"],
        ),
        UISmokeCase(
            case_id="ui-lab-section",
            name="AI Lab section renders",
            category="content",
            objective="Verify the AI Lab destination remains discoverable.",
            path="/#lab",
            expected_text=["AI Lab"],
        ),
        UISmokeCase(
            case_id="ui-digest-section",
            name="Digest section renders",
            category="content",
            objective="Verify the newsletter destination and input are visible.",
            path="/#digest",
            expected_text=["Digest"],
        ),
        UISmokeCase(
            case_id="ui-wide-desktop",
            name="Wide desktop layout renders",
            category="responsive",
            objective="Check the layout at a wide desktop viewport for excessive stretching.",
            viewport_width=1920,
            viewport_height=1080,
            expected_text=["AI Testing & Integration", "Live Feed"],
            design_checkpoint=True,
        ),
        UISmokeCase(
            case_id="ui-tablet-navigation",
            name="Tablet navigation remains usable",
            category="responsive",
            objective="Verify navigation labels remain present near the desktop/mobile breakpoint.",
            viewport_width=768,
            viewport_height=1024,
            expected_text=["Feed", "Explore", "Tools"],
            design_checkpoint=True,
        ),
    ]
